### ISSUE TITLE
Coinigy API for browser

### ISSUE THREAD

**Issue by bernatfortet** [coinigy/api#11]
Hi,

I'm creating a single-page app that would use Coinigy's api.
I was wondering if you have any plan to implement the api for browsers

Hi.

**Comment by ByronAP** [comment]
All API methods both rest and websocket based should be accessible from javascript, what part or method is it exactly that you are having trouble with?

**Comment by robborden** [comment]
Due to CORS security restrictions you cannot currently make API calls directly to our API from a browser.  Doing this requires a Commercial Reseller Agreement to resell  our data and API to your users/customers.  Please contact Coinigy support for more information.
