### ISSUE TITLE
Open Orders - not updating correctly

### ISSUE THREAD

**Issue by jevdiego** [coinigy/api#13]
Hi,

I've noticed some issues with the open orders not updating correctly.
I had placed 4 orders on Liqui. These orders were either cancelled or filled and were now no longer open orders. However, if I requested the open orders through the coinigy API, these orders are all passed back in the response. If I login to Liqui though and view the open orders, there is nothing there. It has been a month since the first order, so I'm assuming there is just some issue between coinigy and Liqui.

I've also noticed that once an order is placed (regardless of the exchange) and I then request the open orders, the 'remaining quantity' is not being updated. E.G. I placed an order on Poloniex which filled 50, but when I request the open order, the remaining quantity is still the full quantity.

Please could you investigate this. The assistance would be appreciated.

Thanks.

**Comment by robborden** [comment]
There is an API call to update the status of all open orders which is currently used by the website but not exposed in the user API.  We plan to expose this functionality in the next 1-2 weeks.  I'll try to update this ticket once it is live.

**Comment by jevdiego** [comment]
OK great. Thanks robborden

**Comment by Lilxam** [comment]
Hey, I'm having the same kind of issue.

"executed_price" is my limit price and not the actual rate it got executed at !
"quantity_remaining" (not updated ?) is equal to "quantity" while the order has been entirely filled.

[order_history] => Array
                (
[0] => Array
                        (
                            [exch_id] => 15
                            [exch_name] => Bittrex
                            [mkt_name] => NEO/USDT
                            [auth_id] => ******
                            **[executed_price] => 31.**  //It's 29 on Bittrex
                            [limit_price] => 31.
                            [order_id] => 16285469
                            [order_type] => Buy
                            [order_price_type] => Limit
                            [order_status] => Executed
                            [quantity] => 0.5
                            **[quantity_remaining] => 0.5**
                            [last_updated] => 2017-09-28 14:07:41
                            [order_time] => 2017-09-28 14:07:41
                            [auth_nickname] => My BITTREX Account
                            [exch_code] => BTRX
                            [display_name] => NEO/USDT
                            [unixtime] => 1506607661
                        )

These issues are quite problematic...

Thanks.

**Comment by jrcleveland** [comment]
Rob,

I think a lot of people are having issues with the API and Open Orders. An order via the API is placed and filled with the exchange, but apparently a response never comes back to allow the open order to be moved into the order history section with the completed info, like the "executed price", which is essential to any kind of automated trading system. The only thing that will make that complete in a timely fashion, is to go to the Coinigy app and click on the Refresh Account option under the Trade tab. Then everything immediately updates. We need the ability to do that via the API so we can send a call to update the order status and balances after we place an order.

It sounds like this is what you were referring to in your comment above, but that was back in September and you said 1-2 weeks. Can you give the community an update on this issue?

Thank you sir!

**Comment by robborden** [comment]
This was already added.  It is called refreshOrders.  I don't think it's documented at the moment but it is identical to refreshBalances.

Thanks,
Rob

**Comment by jrcleveland** [comment]
Thank you sir! I'll test that today and reply back with the results. :)

**Comment by jrcleveland** [comment]
Rob,

That worked perfectly... thank you so much! Keep up the great work at Coinigy!!

- Joe

**Comment by stonaker** [comment]
Is the refreshOrders service available perhaps by another name?  When I attempt to call this service I get 404 not found.

**Comment by stonaker** [comment]
nm, at some point a day or two ago it appeared to start working again.  Thanks!
