### ISSUE TITLE
Cant see results from TICKER channel(C# code)

### ISSUE THREAD

**Issue by freezepro** [coinigy/api#14]
Could you please provide how to call properly(TICKER) also receive All Markets?

Doing this:
var cn = _scc.CreateChannel("TICKER").Subscribe();
cn.OnMessage(TradeData);
or this
var cn0 = _scc.CreateChannel("TICKER-BTRX--ETH--BTC").Subscribe();
cn0.OnMessage(TradeData);

but it doesn't work

**Comment by robborden** [comment]
Please see this blogpost for details:

https://blog.coinigy.com/2017/07/cryptoticker-updated-ticker-websocket-channel-to-be-deprecated/
